// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CMbW9b52tnJ5pVnGuO8rUggUHq219Kw',
    appId: '1:211080641927:android:a53b2997599faed1fb2722',
    messagingSenderId: '211080641927',
    projectId: 'financial-b9426',
    databaseURL: 'https://financial-b9426-default-rtdb.firebaseio.com',
    storageBucket: 'financial-b9426.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNtPZGmmH-FixCE7QXmi26Syv7VRUbPAQ',
    appId: '1:211080641927:ios:5ad786db075a04b8fb2722',
    messagingSenderId: '211080641927',
    projectId: 'financial-b9426',
    databaseURL: 'https://financial-b9426-default-rtdb.firebaseio.com',
    storageBucket: 'financial-b9426.appspot.com',
    iosClientId: '211080641927-ipf3p81rqddtcnlb1pu9om11pua4ssi6.apps.googleusercontent.com',
    iosBundleId: 'com.app360.taxdocs',
  );
}
